pdf:
	@pnpm exec slidev export --format pdf --output ./outputs/pdf/campus-events.pdf

pptx:
	@pnpm exec slidev export --format pptx --output ./outputs/pptx/campus-events.pptx

pptx-editable:
	@pnpm exec slidev export --format pptx-editable --output ./outputs/pptx/campus-events-editable.pptx

png:
	@pnpm exec slidev export --format png --output ./outputs/images/

exall:
	@pnpm exec slidev export --format png --output ./outputs/images/
	@pnpm exec slidev export --format pptx --output ./outputs/pptx/campus-events.pptx
	@pnpm exec slidev export --format pdf --output ./outputs/pdf/campus-events.pdf
	
